package de.rub.nds.eccjava.view;

import java.util.Enumeration;
import org.apache.log4j.Appender;
import org.apache.log4j.Logger;
import de.rub.nds.eccjava.helpers.Bootstrap;

/**
 * 
 * @author Juraj Somorovsky - juraj.somorovsky@rub.de
 */
public class MainGUI extends javax.swing.JFrame {

    private static final Logger LOG = Logger.getLogger(MainGUI.class);
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appController1 = new de.rub.nds.eccjava.controller.AppController();
        BCAttack = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        curveProcessingGUI2 = new de.rub.nds.eccjava.view.curve.CurveLoading();
        curveProcessing1 = new de.rub.nds.eccjava.view.curve.CurveProcessing();
        curveProcessing2 = new de.rub.nds.eccjava.view.curve.CurveProcessing();
        logGUI1 = new de.rub.nds.eccjava.view.log.LogGUI();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Playing with ECC");
        setPreferredSize(new java.awt.Dimension(1500, 850));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        BCAttack.setName(""); // NOI18N
        BCAttack.setPreferredSize(new java.awt.Dimension(1400, 740));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(curveProcessingGUI2, javax.swing.GroupLayout.DEFAULT_SIZE, 1247, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(curveProcessingGUI2, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                .addContainerGap())
        );

        BCAttack.addTab("Curve Loading", jPanel1);

        javax.swing.GroupLayout curveProcessing1Layout = new javax.swing.GroupLayout(curveProcessing1);
        curveProcessing1.setLayout(curveProcessing1Layout);
        curveProcessing1Layout.setHorizontalGroup(
            curveProcessing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curveProcessing1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(curveProcessing2, javax.swing.GroupLayout.DEFAULT_SIZE, 1235, Short.MAX_VALUE))
        );
        curveProcessing1Layout.setVerticalGroup(
            curveProcessing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curveProcessing1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(curveProcessing2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BCAttack.addTab("Curve Processing", curveProcessing1);
        BCAttack.addTab("Log Viewer", logGUI1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BCAttack, javax.swing.GroupLayout.DEFAULT_SIZE, 1255, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BCAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 679, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
	Bootstrap.onStop();
    }// GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
	Bootstrap.onStart();
    }// GEN-LAST:event_formWindowOpened

    /**
     * @param args
     *            the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	// <editor-fold defaultstate="collapsed"
	// desc=" Look and feel setting code (optional) ">
	/*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the
	 * default look and feel. For details see
	 * http://download.oracle.com/javase
	 * /tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
	    LOG.warn(ex.getLocalizedMessage(), ex);
	}

	Logger log = Logger.getRootLogger();

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new MainGUI().setVisible(true);
	    }
	});

	Enumeration app = log.getAllAppenders();
	while (app.hasMoreElements()) {
	    Appender a = (Appender) app.nextElement();
	}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane BCAttack;
    private de.rub.nds.eccjava.controller.AppController appController1;
    private de.rub.nds.eccjava.view.curve.CurveProcessing curveProcessing1;
    private de.rub.nds.eccjava.view.curve.CurveProcessing curveProcessing2;
    private de.rub.nds.eccjava.view.curve.CurveLoading curveProcessingGUI2;
    private javax.swing.JPanel jPanel1;
    private de.rub.nds.eccjava.view.log.LogGUI logGUI1;
    // End of variables declaration//GEN-END:variables
}
